---
- name: testloopback
  hosts: all
  gather_facts: no

  tasks:
  - name: test tao loopback
    ios_l3_interface:
     name: loopback {{ item.number }}
     ipv4: 10.0.{{ item.number }}.1/24
    with_items:
     - { number: 1}
     - { number: 2}
     - { number: 3}
        
   - debug: var=show_ip.stdout_lines
